# PinchBench NanoBotAgent Image
# Built on clawbase-nanobot:v1
#
# Build: docker build -f docker/pinchbench/Dockerfile -t clawbase-nanobot:v1 .
# NOTE: This just inherits from base, OpenClawPro is mounted at runtime

FROM clawbase-nanobot:v1
